<?php

namespace Database\Seeders;

use App\Models\Link;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Intervention\Image\Drivers\Imagick\Driver;
use Intervention\Image\ImageManager;

class LinkSeeder extends Seeder
{
    protected ImageManager $manager;

    public function run(): void
    {
        Storage::disk('public')->deleteDirectory('links/favicons');
        File::ensureDirectoryExists(Storage::disk('public')->path('links/favicons'));

        $this->manager = ImageManager::usingDriver(Driver::class);

        foreach ($this->links() as $link) {
            Link::create([
                'favicon' => $this->fetchFavicon($link['url']),
                'url' => $link['url'],
                'description' => $link['description'] ?: null,
            ]);
        }
    }

    protected function fetchFavicon(string $url): string
    {
        $host = parse_url($url, PHP_URL_HOST);

        $response = Http::timeout(10)->get('https://www.google.com/s2/favicons', [
            'domain' => $host,
            'sz' => 128,
        ]);

        $filename = Str::uuid();

        $this->manager->decode($response->body())
            ->cover(32, 32)
            ->save(
                Storage::disk('public')->path("links/favicons/{$filename}.webp"),
                quality: 85,
            );

        return "links/favicons/{$filename}.webp";
    }

    protected function links(): array
    {
        return [
            ['url' => 'https://wttr.in/', 'description' => 'ASCII weather'],
            ['url' => 'https://noneventivefeedback.neocities.org/linkfarm', 'description' => 'Links page of Noneventive Feedback'],
            ['url' => 'https://vegan-recipes.org/', 'description' => 'Simple HTML vegan recipes'],
            ['url' => 'https://special.fish/garden', 'description' => 'Community based light social media'],
            ['url' => 'https://www.ocf.berkeley.edu/~abhishek/chicmath.htm', 'description' => 'An old list of math books'],
            ['url' => 'https://nocss.club/', 'description' => 'A list of websites without CSS'],
            ['url' => 'https://thricegreat.neocities.org/', 'description' => 'A sort of plaintext blog'],
            ['url' => 'https://covers.brunoimbrizi.com', 'description' => 'Album cover search engine based on visual similarity'],
            ['url' => 'https://nabiu.studio/', 'description' => 'The digital garden of Núria'],
            ['url' => 'http://www.celer.jp/', 'description' => 'Celer\'s website'],
            ['url' => 'https://transit.jp/regular/tunisia/misato-shimizu_sauna_vol15/', 'description' => 'A cool japanese magazine'],
            ['url' => 'https://blog.jim-nielsen.com/2026/small-html-pages/', 'description' => 'An article about using small html pages'],
            ['url' => 'https://architectureofsilence.com/', 'description' => 'A bunch of small posts about the virtues of silence'],
            ['url' => 'https://practicalbetterments.com/', 'description' => 'A list of small things to make your life better'],
            ['url' => 'https://keliz.xyz/', 'description' => 'A strange green labyrinth'],
            ['url' => 'https://mindyseu.com/', 'description' => 'The website of Mindy Seu'],
            ['url' => 'https://www.spottedinprod.com/', 'description' => 'A showcase of mobile app designs'],
            ['url' => 'https://geokash.com/', 'description' => 'The website of Katarina Lingat'],
            ['url' => 'https://valuesbased.software/', 'description' => 'Links to a few talks about simple web topics'],
            ['url' => 'https://vimm.net/vault/DS/', 'description' => 'Roms for the DS'],
            ['url' => 'http://jeuxnintendods.free.fr/', 'description' => 'French roms for the DS'],
            ['url' => 'https://farayan.me/', 'description' => 'The website of Fara Yan'],
            ['url' => 'https://txt.dev/ana-piligrim/slow-design-in-a-fast-world', 'description' => 'Article about slow design in a fast world'],
            ['url' => 'https://keyavadgama.com', 'description' => 'The website of Keya Vadgama'],
            ['url' => 'https://mac.are.na/', 'description' => 'Community based playlist tool of Are.na'],
            ['url' => 'https://textonly.website/', 'description' => 'A list of mostly text based websites'],
            ['url' => 'https://unwissen.blog/', 'description' => 'A German blog'],
            ['url' => 'https://blog.absurdpirate.com/', 'description' => 'The blog of Absurd Pirate'],
            ['url' => 'https://grainrad.com/', 'description' => 'An image modification tool'],
            ['url' => 'https://www.shader.se/', 'description' => 'Website of Shader Development Studio'],
            ['url' => 'https://www.bguillaume.info/', 'description' => 'Portfolio site of Guillaume, designer at Anagram'],
            ['url' => 'https://www.arcoty.pe/', 'description' => 'A font searching tool'],
            ['url' => 'https://thehtml.review', 'description' => 'The HTML review'],
            ['url' => 'https://tangiblelife.net/', 'description' => 'A cute little blog'],
            ['url' => 'https://smallcypress.bearblog.dev/blog/', 'description' => 'Small cypress\'s blog'],
            ['url' => 'https://www.write-on.org/', 'description' => 'An old style website'],
            ['url' => 'https://home.elliott.computer/', 'description' => 'The list of all of elliott\'s work on the web'],
            ['url' => 'https://www.nicksimson.com/posts/2026-lost-in-the-met', 'description' => 'An article recollecting visiting the MET'],
            ['url' => 'https://cloudlord.management/', 'description' => 'An internet surreal estate holding company'],
            ['url' => 'https://bitmap.designfamilymarket.com/#/', 'description' => 'A bitmap image edition tool'],
            ['url' => 'https://www.ko-collective.com/', 'description' => 'The website of a dope production company'],
            ['url' => 'https://denimtears.com/', 'description' => 'Fashion brand website'],
            ['url' => 'https://blog.geocities.institute/', 'description' => 'One Terabyte of Kilobyte Age'],
            ['url' => 'https://lilguy.net/', 'description' => 'Website for a cool looking wearable'],
            ['url' => 'https://50centadjustedforinflation.com/', 'description' => '50 cents adjusted for inflation'],
            ['url' => 'https://www.ciggies.app/', 'description' => 'Chinese cigarette museum'],
            ['url' => 'https://www.lochieaxon.com/', 'description' => 'Website of Lochie Axon'],
            ['url' => 'https://compress.lochie.me/', 'description' => 'A tool to compress videos on and for the web'],
            ['url' => 'https://www.wuweicoffee.com/blogs/blog/zen-and-the-art-of-coffee-a-mindful-morning-ritual', 'description' => 'An article about the zen act of making coffee'],
            ['url' => 'https://2011-present.bendenzer.com', 'description' => 'Archive of Ben Denzer\'s life in pictures'],
            ['url' => 'https://www.emilyz.sh/', 'description' => 'Emily Zhang\'s website'],
            ['url' => 'https://lelezhang.design/', 'description' => 'The website of Lele Zhang'],
            ['url' => 'https://futuraresistenza.bandcamp.com/', 'description' => 'The bandcamp of a small record label'],
            ['url' => 'https://permacomputing.net/principles/', 'description' => 'Principles for permacomputing'],
            ['url' => 'https://leseditionsdesmondesafaire.net/produit/vivre-avec-le-trouble/', 'description' => 'Single page of a good book'],
            ['url' => 'https://wildproject.org/livres/les-diplomates-poche', 'description' => 'Page of the book "Les diplomates" by Baptiste Morizot'],
            ['url' => 'https://entremonde.net/reenchanter-le-monde', 'description' => 'Réenchanter le monde'],
            ['url' => 'https://lltg.co/', 'description' => 'Arun\'s photographs'],
            ['url' => 'https://www.alexandriamasse.com/', 'description' => 'Alexandria Masse\'s crochet website'],
            ['url' => 'https://emilysneddon.com/fran-sans-essay', 'description' => 'Essay about the font on the displays of SF light rail vehicles'],
            ['url' => 'https://brianlovin.com/', 'description' => 'Brian Lovin\'s website'],
            ['url' => 'https://nondairydiary.com/recipe/vegan-vol-au-vent', 'description' => 'Vegan vol-au-vent recipe'],
            ['url' => 'https://app.electricitymaps.com/map/live/fifteen_minutes', 'description' => 'Electricity map'],
            ['url' => 'https://www.nicchan.me', 'description' => 'Website of Nic Chan'],
            ['url' => 'https://gkeenan.co/avgb/', 'description' => 'Keenan\'s blog'],
            ['url' => 'https://ericwbailey.website/published/', 'description' => 'Blog of Eric W Bailey'],
            ['url' => 'https://fershad.com/writing', 'description' => 'Blog of Fershad Irani'],
            ['url' => 'https://piccalil.li/blog/taking-a-shot-at-the-double-focus-ring-problem-using-modern-css/', 'description' => 'An article about focus rings'],
            ['url' => 'https://ifyouknewmewouldyoulove.me/', 'description' => 'Chia\'s website asks If you knew me would you love me?'],
            ['url' => 'https://kayserifserif.place/', 'description' => 'The website of Katherine Yang'],
            ['url' => 'https://aartaka.me/', 'description' => 'Artyom\'s cahotic blog'],
            ['url' => 'https://jeffhuang.com/designed_to_last/', 'description' => 'A Manifesto for Preserving Content on the Web'],
            ['url' => 'https://williamdenis.be/', 'description' => 'Website of William Denis'],
            ['url' => 'https://juliedelfour.com/', 'description' => 'Website of Julie Delfour'],
            ['url' => 'https://hippolytelesseliers.be/', 'description' => 'Website of Hippolyte Lesseliers'],
            ['url' => 'https://roscosmic.com/', 'description' => 'Speculative space agency'],
            ['url' => 'https://abcdinamo.com/', 'description' => 'Dynamo typefaces'],
            ['url' => 'https://f37foundry.com/fonts/f37-caligari', 'description' => 'F37 foundry'],
            ['url' => 'https://www.205.tf/typefaces', 'description' => '205 Typefaces'],
            ['url' => 'https://colorpalette.pro/', 'description' => 'Color palette maker'],
            ['url' => 'https://www.incommonwith.com/', 'description' => 'Website with a cool light effect'],
            ['url' => 'https://tarneo.fr/posts/minimal_web/', 'description' => 'A post about the minimal web'],
            ['url' => 'https://theoatmeal.com/comics/unhappy', 'description' => 'A comic about being unhappy'],
            ['url' => 'https://tink.uk/perceived-affordances-and-the-functionality-mismatch/', 'description' => 'Article about affordances'],
            ['url' => 'https://fossheim.io/writing/posts/accessible-theme-picker-html-css-js/', 'description' => 'Making an accessible theme picker'],
            ['url' => 'https://pjonori.blog/posts/i-dont-want-your-email/', 'description' => 'A hate post about newsletters'],
            ['url' => 'https://mtwb.blog/posts/2025/blaugust2025/not-every-blog-post-needs-to-be-epic/', 'description' => 'A post about simple posts'],
            ['url' => 'https://kedara.eu/organising-feeds-permaculture', 'description' => 'Permaculture applied to RSS'],
            ['url' => 'https://cursor.com/', 'description' => 'I hate Cursor but their website looks good'],
            ['url' => 'https://eva.town/', 'description' => 'The website of Ky Decker'],
            ['url' => 'https://chotrin.org/philosophy/unreachable.html', 'description' => 'an ode to being unreachable'],
            ['url' => 'https://birming.com/', 'description' => 'Website of Robert Birming'],
            ['url' => 'https://tonsky.me/blog/centering/', 'description' => 'An article about centering divs'],
            ['url' => 'https://www.holovaty.com/writing/chatgpt-fake-feature/', 'description' => 'An article about fake AI features having to be made'],
            ['url' => 'https://tonsky.me/blog/lockfiles/', 'description' => 'An article about versionning'],
            ['url' => 'https://rscottjones.com/getting-the-most-out-of-a-bad-situation/', 'description' => 'Getting the most out of a bad situation'],
            ['url' => 'https://birming.com/2025/09/21/publish-dont-polish/', 'description' => 'The publish don\'t polish philosophy'],
            ['url' => 'http://kira.eight45.net/deconstruction-mindset.html', 'description' => 'About viewing objects for more than their purpose'],
            ['url' => 'https://romi.link', 'description' => 'The website of Romina Malta'],
            ['url' => 'https://midnightpond.com', 'description' => 'Website of poems'],
            ['url' => 'https://www.door.link', 'description' => 'Musical doors'],
            ['url' => 'https://romi.link/journal', 'description' => 'The journal or Romina Malta'],
            ['url' => 'https://jpolak.org/photo/best-macos-text-editors/', 'description' => 'An article discussing the best macos text editors'],
            ['url' => 'https://www.shipsltd.co.jp/pages/sp_50th_anniversary.aspx', 'description' => 'A website made with strings'],
            ['url' => 'https://www.nan.fyi/database', 'description' => 'An article explaining how to build your own database'],
            ['url' => 'https://emmiwu.com/playground', 'description' => 'Emi Wu\'s infinite canvas of images'],
            ['url' => 'https://stephango.com/style', 'description' => 'Style is a set of constraints that you stick to'],
            ['url' => 'https://stephango.com/understand', 'description' => 'Article about delegating understanding'],
            ['url' => 'https://www.netmeister.org/blog/the-art-of-plain-text.html', 'description' => 'The Art of Plain Text'],
            ['url' => 'https://generaux.services/projects', 'description' => 'Services Généraux'],
            ['url' => 'https://gijs.garden/#', 'description' => 'A Garden of Care Tools'],
            ['url' => 'https://www.dayroselane.com/hydrants', 'description' => 'The hydrant directory'],
            ['url' => 'https://ainsleyromero.com/', 'description' => 'The website of Ainsley Romero'],
            ['url' => 'https://c82.net/mineralogy/#', 'description' => 'Pretty rocks rock'],
            ['url' => 'https://findmy.vitra.com/en-en/questionnaire/chairs', 'description' => 'A delightful office chair finder'],
            ['url' => 'http://whispersgame.com/', 'description' => 'A sequential art game'],
            ['url' => 'https://www.benoitjeannet.ch/', 'description' => 'The portfolio of Benoit Jeannet'],
            ['url' => 'https://huynhkristi.com/', 'description' => 'Kristi Huynh\'s website'],
            ['url' => 'https://kaiem.ch/', 'description' => 'Cool bags'],
            ['url' => 'https://rotating.parts/', 'description' => 'Rotating parts'],
            ['url' => 'https://veronique.ink', 'description' => 'The website of Véronique'],
            ['url' => 'https://landonorris.com', 'description' => 'Presentation website for Lando Norris. It\'s disco'],
            ['url' => 'https://tarneo.fr/', 'description' => 'Tarneo\'s blog'],
            ['url' => 'https://messenger.abeto.co/', 'description' => 'A web based videogame'],
            ['url' => 'https://departure.blog', 'description' => 'A parenthetical departure'],
            ['url' => 'https://oliverobscure.xyz/', 'description' => 'The blog of Oliver'],
            ['url' => 'https://pjonori.blog/', 'description' => 'PJ Onori\'s blog'],
            ['url' => 'https://lmnt.me/', 'description' => 'Louie Mantia\'s website'],
            ['url' => 'https://johnprovencher.com/', 'description' => 'John Provencher\'s portfolio'],
            ['url' => 'https://spencer.place/', 'description' => 'The website of Spencer Chang'],
            ['url' => 'https://guillaumevg.substack.com/', 'description' => 'Great vegan recipes'],
            ['url' => 'https://walknotes.com/', 'description' => 'Walknotes'],
            ['url' => 'https://www.makingsoftware.com/', 'description' => 'A web book about making software'],
            ['url' => 'https://internetphonebook.net/', 'description' => 'Internet phonebook'],
            ['url' => 'https://reubenson.com/', 'description' => 'The website of Reuben Son'],
            ['url' => 'https://atto.si/', 'description' => 'Website of Atto'],
            ['url' => 'https://patrickfry.co.uk/', 'description' => 'Patrick Fry\'s website'],
            ['url' => 'https://peopleandblogs.com/', 'description' => 'People and blogs interviews'],
            ['url' => 'https://carlbarenbrug.com/', 'description' => 'The website of Carl Barenbrug'],
            ['url' => 'https://hturan.com/writing/complex-numbers-glsl', 'description' => 'An article about visualizing complex numbers using GLSL'],
            ['url' => 'https://alexharri.com/blog/webgl-gradients', 'description' => 'An article about WEBGL gradients'],
            ['url' => 'https://www.mmmx.cloud/', 'description' => 'Nim\'s Memex'],
            ['url' => 'https://os.ryo.lu/', 'description' => 'Ryo OS'],
            ['url' => 'https://www.mayabakir.com/desktop.html', 'description' => 'Website of Maya Bakir'],
            ['url' => 'https://aintnotrash.com/en', 'description' => 'A vintage furniture store'],
            ['url' => 'https://ericreh.de/en', 'description' => 'The website of Eric Reh'],
            ['url' => 'https://mutantx.bip-liege.org/', 'description' => 'Mutantx'],
            ['url' => 'https://www.pathem.es/', 'description' => 'Website for a photo book'],
            ['url' => 'https://koto.studio/work/amazon/', 'description' => 'Koto studio Amazon case study'],
            ['url' => 'https://godly.website/', 'description' => 'Design inspiration'],
            ['url' => 'https://loadmo.re/', 'description' => 'Mobile site design inspiration'],
            ['url' => 'https://httpster.net/', 'description' => 'Website design inspiration'],
            ['url' => 'https://minimal.gallery/', 'description' => 'Website design inspiration'],
            ['url' => 'https://www.siteinspire.com/', 'description' => 'Website design inspiration'],
            ['url' => 'https://maxibestof.one/', 'description' => 'Website design inspiration'],
            ['url' => 'https://deadsimplesites.com/', 'description' => 'The most minimal sites on the web, curated in one place.'],
            ['url' => 'https://www.are.na/anne-lee/alt-web-ddwo8t9ndfw', 'description' => 'A cool are.na channel'],
            ['url' => 'https://www.funnyfriends.com/celestial', 'description' => 'A cute plushie shop'],
            ['url' => 'https://appstacks.club/', 'description' => 'Talks about the stacks behind apps'],
            ['url' => 'https://test.roelof.info/', 'description' => 'Roel roscam abbing'],
            ['url' => 'https://www.verdeil.net/', 'description' => 'The website of Marie Verdeil'],
            ['url' => 'https://www.specs.work/', 'description' => 'A architecture studio website'],
            ['url' => 'https://meyboom.space/', 'description' => 'Meyboom Artist Run Spaces'],
            ['url' => 'https://surma.dev/things/ditherpunk/', 'description' => 'Article about ditherpunk'],
            ['url' => 'https://jamesg.blog/', 'description' => 'Jame\'s coffee blog'],
            ['url' => 'https://solar.lowtechmagazine.com/', 'description' => 'A solar powered website'],
            ['url' => 'https://www.figma.com/blog/making-space-for-a-handmade-web/', 'description' => 'Figma\'s on handmade web — How ironic'],
            ['url' => 'https://gjphenry.be/', 'description' => 'The website of GJP'],
            ['url' => 'https://jonathanrixhon.dev/', 'description' => 'The website of Jonathan'],
            ['url' => 'https://leloup.dev/', 'description' => 'The website of Void'],
            ['url' => 'https://melonking.net/', 'description' => 'Melon king\'s kingdom'],
            ['url' => 'https://justinjay.wang/methods-for-random-gradients/', 'description' => 'An article about generating gradients'],
            ['url' => 'https://dev.to/thepassle/events-are-the-shit-b3i', 'description' => 'An article about js events'],
            ['url' => 'https://grugbrain.dev/', 'description' => 'Grug brain dev'],
            ['url' => 'https://abhisaha.com/blog/exploring-browser-rendering-process', 'description' => 'Article explaining browser rendering'],
            ['url' => 'https://longform.asmartbear.com/slc/', 'description' => 'MVP < SLC'],
            ['url' => 'https://btxx.org/', 'description' => 'Bradley Taunt\'s website'],
            ['url' => 'https://modalzmodalzmodalz.com/', 'description' => 'A website against modals'],
            ['url' => 'https://marioecg.com/', 'description' => 'Mario Carrillo\'s website'],
            ['url' => 'https://www.easing.dev/', 'description' => 'An easing generator'],
            ['url' => 'https://www.cosmos.so/cosmos/genesis/canvas', 'description' => 'Cosmos Genesis'],
            ['url' => 'https://www.stitson.com/pub/book_html/node89.html', 'description' => 'Ed, the line editor'],
            ['url' => 'https://michaeluloth.com/neovim-switch-configs/', 'description' => 'How to switch configs in nvim'],
            ['url' => 'https://blog.jim-nielsen.com/2024/sanding-ui/', 'description' => 'Article about clicking over and over'],
            ['url' => 'https://arc.net/search', 'description' => 'Arc mobile browser'],
            ['url' => 'https://cursor.design/', 'description' => 'Copyable macos cursors'],
            ['url' => 'https://teenage.engineering/products/ep-1320', 'description' => 'A modern medieval instrument'],
            ['url' => 'https://motion-primitives.com/', 'description' => 'UI kit to make beautiful, animated interfaces, faster.'],
            ['url' => 'https://linusrogge.com/', 'description' => 'Linus Rogge\'s website'],
            ['url' => 'https://inventory.linusrogge.com/', 'description' => 'The inventory of Linus Rogge'],
            ['url' => 'https://valuable-colleagues-147045.framer.app/', 'description' => 'It\'s red, it\'s cool'],
            ['url' => 'https://www.beciorpin.com/', 'description' => 'The website of Beci Orpin'],
            ['url' => 'https://thedesignfiles.net/2022/08/studio-visit-beci-orpin-ellie-king', 'description' => 'An article visiting Beci Orpin\'s studio'],
            ['url' => 'https://www.wimpdecaf.com/', 'description' => 'Decaf brand'],
            ['url' => 'https://naotofukasawa.com/', 'description' => 'The website of Nekoto Fukasawa'],
            ['url' => 'https://www.citationneeded.news/we-can-have-a-different-web/', 'description' => 'An article about a different web'],
            ['url' => 'https://oem.care/', 'description' => 'A new drugstore'],
            ['url' => 'https://nicolasgallagher.com/about-html-semantics-front-end-architecture/', 'description' => 'Old article on semantics'],
            ['url' => 'https://cameronaskin.com/', 'description' => 'The website of Cameron Askin'],
            ['url' => 'https://www.interface.watch/', 'description' => 'WatchOs inspiration'],
            ['url' => 'https://airtraveldesign.guide/Guide', 'description' => 'How to design plane related stuff'],
            ['url' => 'https://toonvandenbos.com/', 'description' => 'The website of Toon Van Den Bos'],
            ['url' => 'https://jakub.kr/', 'description' => 'The website of Jakub Krehel'],
            ['url' => 'https://higherorderco.com/', 'description' => 'Website for the bend programming language'],
            ['url' => 'https://littlefatboy.com/', 'description' => 'Asian American cooking'],
            ['url' => 'https://gomakethings.com/', 'description' => 'Chris Ferdinandi\'s website'],
            ['url' => 'https://www.cameronsworld.net/', 'description' => 'A tribute to geocities'],
            ['url' => 'https://softglossary.space/', 'description' => 'A place to learn web dev'],
            ['url' => 'https://barbaraschussmann.de/', 'description' => 'The website of Barbara Schussmann'],
            ['url' => 'https://pierre.co/', 'description' => 'Like github but cool'],
            ['url' => 'https://www.lemarais407.be/', 'description' => 'Co-working space in Brussels'],
            ['url' => 'https://emilkowal.ski/ui/great-animations', 'description' => 'Emil Kowalski article on great animations'],
            ['url' => 'https://animejs.com/', 'description' => 'JS animation library'],
            ['url' => 'https://slrncl.com/', 'description' => 'The website of Nicolas Solerieu'],
            ['url' => 'https://blogroll.org/', 'description' => 'A list of blogs'],
            ['url' => 'https://manuelmoreale.com', 'description' => 'The website of Manuel Moreale'],
        ];
    }
}
